# Generated by Django 4.2.1 on 2023-05-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='CorporateAssets.company')),
            ],
        ),
        migrations.CreateModel(
            name='Asset_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('checked_out_date', models.DateTimeField()),
                ('checked_in_date', models.DateTimeField(blank=True, null=True)),
                ('condition_on_checkout', models.CharField(max_length=100)),
                ('condition_on_checking', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporateAssets.asset')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporateAssets.employee')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorporateAssets.employee'),
        ),
    ]
